// <auto-generated />
using System;
using CVTech.Modules.AppelOffreFreelance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppelOffreFreelance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppelOffreDbContext))]
    partial class AppelOffreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domain.Entites.AppelOffre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BudgetMax")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contexte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("DomaineMetier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppelsOffre");
                });

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domain.Entites.PropositionFreelance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AppelOffreId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeEstimeeJours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Methodologie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TauxJournalierMoyen")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Propositions");
                });
#pragma warning restore 612, 618
        }
    }
}
