// <auto-generated />
using System;
using CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogueEmploi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogueEmploiDbContext))]
    partial class CatalogueEmploiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domain.Entites.AnnonceEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomaineMetier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeContrat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Annonces");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domain.Entites.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnnonceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurriculumVitaeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateDepot")
                        .HasColumnType("TEXT");

                    b.Property<string>("LettreMotivation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Candidatures");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domain.Entites.CurriculumVitae", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DerniereModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurriculumsVitae");
                });
#pragma warning restore 612, 618
        }
    }
}
